FROM alpine:3.20.0 as certs
RUN apk --update add ca-certificates curl
RUN curl -L https://github.com/soulteary/mini-shortener/raw/main/rules -o /rules

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY mini-shortener /usr/bin/mini-shortener
WORKDIR /app
COPY --from=certs /rules /app/rules
EXPOSE 8901/tcp
ENTRYPOINT ["/usr/bin/mini-shortener"]